    const statesList = [
        'Andaman and Nicobar Islands',
        'Andhra Pradesh',
        'Arunachal Pradesh',
        'Assam',
        'Bihar',
        'Chandigarh',
        'Chhattisgarh',
        'Dadra and Nagar Haveli',
        'Daman and Diu',
        'Delhi',
        'Goa',
        'Gujarat',
        'Haryana',
        'Himachal Pradesh',
        'Jammu and Kashmir',
        'Jharkhand',
        'Karnataka',
        'Kerala',
        'Ladakh',
        'Lakshadweep',
        'Madhya Pradesh',
        'Maharashtra',
        'Manipur',
        'Meghalaya',
        'Mizoram',
        'Nagaland',
        'Odisha',
        'Puducherry',
        'Punjab',
        'Rajasthan',
        'Sikkim',
        'Tamil Nadu',
        'Telangana',
        'Tripura',
        'Uttar Pradesh',
        'Uttarakhand',
        'West Bengal'
    ];

    const citiesByState = {
        'Andaman and Nicobar Islands': ['Port Blair','Havelock Island','Neil Island','Long Island','Diglipur','Mayabunder','Rangat','Little Andaman','Great Nicobar','Campbell Bay','Car Nicobar','Malappuram','Bamboo Flat','Garacharma','Prothrapur','Marthandam','Bathu Basti','Kamorta','North Passage Island','Nancowry','Shibpur','Katchal','Teressa','Ponding','Aberdeen Bazaar','Port Blair H.O','Port Blair G.P.O'],
        'Andhra Pradesh': ['Visakhapatnam', 'Vijayawada', 'Guntur', 'Nellore', 'Kurnool', 'Rajahmundry', 'Tirupati', 'Kadapa', 'Anantapur', 'Vizianagaram', 'Eluru', 'Ongole', 'Machilipatnam', 'Adoni', 'Tenali', 'Proddatur', 'Chittoor', 'Hindupur', 'Bhimavaram', 'Madanapalle', 'Amaravati', 'Srikakulam', 'Kakinada', 'Gudivada', 'Tadepalligudem', 'Chilakaluripet', 'Yemmiganur', 'Adoni', 'Narasaraopet', 'Tadipatri'],
        'Arunachal Pradesh': ['Itanagar', 'Naharlagun', 'Pasighat', 'Namsai', 'Roing', 'Tezu', 'Ziro', 'Along', 'Bomdila', 'Daporijo', 'Aalo', 'Khonsa', 'Anini', 'Tawang', 'Seppa', 'Yingkiong', 'Changlang', 'Mechuka', 'Bhalukpong', 'Hayuliang', 'Naharlagun', 'Bordumsa', 'Jairampur', 'Nampong', 'Changlang', 'Pasighat'],
        'Assam': ['Guwahati', 'Silchar', 'Dibrugarh', 'Jorhat', 'Nagaon', 'Tinsukia', 'Tezpur', 'Bongaigaon', 'Dhubri', 'Sibsagar', 'Goalpara', 'Barpeta', 'North Lakhimpur', 'Karimganj', 'Hailakandi', 'Nalbari', 'Lanka', 'Morigaon', 'Nagaon', 'Karimganj', 'Diphu', 'Sivasagar', 'Haflong', 'Nagaon', 'Kokrajhar', 'Dhubri', 'Hojai', 'Dibrugarh', 'Jorhat', 'Sibsagar', 'Bongaigaon', 'Tinsukia', 'Dhubri', 'Silchar', 'Jorhat', 'Tezpur', 'Nagaon', 'Silchar', 'Dibrugarh', 'Hailakandi', 'Guwahati', 'Bongaigaon', 'Dhubri'],
        'Bihar': ['Patna', 'Gaya', 'Bhagalpur', 'Muzaffarpur', 'Purnia', 'Darbhanga', 'Arrah', 'Begusarai', 'Katihar', 'Munger', 'Chhapra', 'Danapur', 'Saharsa', 'Sasaram', 'Hajipur', 'Dehri', 'Siwan', 'Motihari', 'Nawada', 'Bagaha', 'Buxar', 'Kishanganj', 'Sitamarhi', 'Jamalpur', 'Jehanabad', 'Aurangabad', 'Lakhisarai', 'Jamui', 'Araria', 'Forbesganj', 'Supaul', 'Gopalganj', 'Madhubani', 'Bettiah', 'Saharsa', 'Sultanganj', 'Sheikhpura', 'Rosera', 'Mokama', 'Barh', 'Barauli', 'Maner', 'Bihar Sharif'],
        'Chandigarh':['Chandigarh'],
        'Chhattisgarh': ['Raipur', 'Bhilai', 'Bilaspur', 'Korba', 'Durg', 'Rajnandgaon', 'Raigarh', 'Jagdalpur', 'Ambikapur', 'Chirmiri'],
        'Dadra and Nagar Haveli': ['Silvassa', 'Amli', 'Naroli', 'Dadra'],
        'Daman and Diu': ['Daman', 'Diu'],
        'Delhi': ['Delhi'],
        'Goa': ['Panaji', 'Margao', 'Vasco da Gama', 'Mapusa', 'Ponda', 'Bicholim', 'Curchorem', 'Cuncolim', 'Quepem', 'Sanguem', 'Valpoi'],
        'Gujarat': ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Junagadh', 'Gandhinagar', 'Gandhidham', 'Nadiad', 'Morbi', 'Anand', 'Surendranagar', 'Bharuch', 'Navsari', 'Valsad', 'Vapi', 'Ankleshwar', 'Mehsana', 'Amreli', 'Dahod', 'Godhra', 'Palanpur', 'Veraval', 'Porbandar', 'Bhuj', 'Gondal', 'Botad', 'Sidhpur'],
        'Haryana': ['Faridabad', 'Gurgaon', 'Panipat', 'Ambala', 'Yamunanagar', 'Rohtak', 'Hisar', 'Karnal', 'Sonipat', 'Panchkula', 'Bhiwani', 'Sirsa', 'Bahadurgarh', 'Jind', 'Thanesar', 'Kaithal', 'Rewari', 'Palwal', 'Hansi', 'Narnaul', 'Fatehabad', 'Gohana', 'Tohana', 'Narwana', 'Ladwa', 'Mahendragarh', 'Safidon', 'Kosli', 'Shahbad'],
        'Himachal Pradesh': ['Shimla', 'Mandi', 'Solan', 'Dharamshala', 'Una', 'Kullu', 'Chamba', 'Hamirpur', 'Bilaspur', 'Nahan', 'Paonta Sahib', 'Nurpur', 'Palampur', 'Sundarnagar', 'Mandi', 'Rampur', 'Bhuntar', 'Keylong', 'Joginder Nagar', 'Sarkaghat', 'Nagrota Bagwan', 'Banjar', 'Chamba', 'Dalhousie', 'Manali', 'Kangra', 'Baddi', 'Parwanoo', 'Nalagarh'],
        'Jammu and Kashmir': ['Srinagar', 'Jammu', 'Anantnag', 'Baramulla', 'Kathua', 'Pulwama', 'Udhampur', 'Rajauri', 'Sopore', 'Punch', 'Kupwara', 'Bandipora', 'Doda', 'Handwara', 'Samba', 'Kargil', 'Leh', 'Poonch', 'Ramban', 'Kishtwar', 'Shopian', 'Ganderbal', 'Reasi', 'Kulgam', 'Akhnoor', 'Samba', 'Katra', 'Banihal', 'Mirpur', 'Sumbal'],
        'Jharkhand': ['Ranchi', 'Jamshedpur', 'Dhanbad', 'Bokaro Steel City', 'Deoghar', 'Phusro', 'Hazaribagh', 'Giridih', 'Ramgarh', 'Medininagar (Daltonganj)', 'Chirkunda', 'Jhumri Tilaiya', 'Saunda', 'Sahibganj', 'Godda', 'Chatra', 'Garhwa', 'Gumia', 'Pakaur', 'Jamtara', 'Dumka', 'Chaibasa', 'Jagannathpur', 'Kanke', 'Chaibasa', 'Chakradha'],
        'Karnataka': ['Bangalore', 'Hubli', 'Mangalore', 'Gulbarga', 'Belgaum', 'Davanagere', 'Bellary', 'Bijapur', 'Shimoga', 'Tumkur', 'Raichur', 'Bidar', 'Hospet', 'Hassan', 'Gadag-Betageri', 'Robertson Pet', 'Chitradurga', 'Kolar', 'Mandya', 'Chikmagalur', 'Gangawati', 'Bagalkot', 'Ranebennuru', 'Sirsi', 'Karwar', 'Jamkhandi', 'Udupi', 'Puttur', 'Lingsugur', 'Hospet', 'Athni', 'Gokak', 'Pandavapura', 'Magadi', 'Shrirangapattana', 'Sindhnur', 'Tekkalakote', 'Savanur', 'Rabkavi Banhatti', 'Mulbagal', 'Sidlaghatta'],
        'Kerala': ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Kollam', 'Thrissur', 'Alappuzha', 'Palakkad', 'Malappuram', 'Kannur', 'Thalassery', 'Manjeri', 'Neyyattinkara', 'Kasaragod', 'Kottayam', 'Vadakara', 'Thiruvalla', 'Kannur', 'Kollam', 'Thalassery', 'Ponnani', 'Tirur', 'Kasaragod', 'Aluva', 'Kayamkulam', 'Punalur', 'Malappuram', 'Attingal', 'Nilambur', 'Payyannur', 'Mattannur', 'Palakkad', 'Chalakudy', 'Kodungallur', 'Changanassery', 'Cherthala', 'Perinthalmanna', 'Kottakkal', 'Kunnamkulam', 'Koyilandy'],
        'Ladakh': ['leh','Kargil'],
        'Lakshadweep': ['Kavaratti', 'Agatti', 'Minicoy', 'Andrott', 'Amini', 'Kadmat', 'Kalpeni', 'Chetlat', 'Bitra', 'Kiltan'],
        'Madhya Pradesh': ['Indore', 'Bhopal', 'Jabalpur', 'Gwalior', 'Ujjain', 'Sagar', 'Dewas', 'Satna', 'Ratlam', 'Rewa', 'Murwara (Katni)', 'Singrauli', 'Burhanpur', 'Khandwa', 'Morena', 'Bhind', 'Guna', 'Shivpuri', 'Vidisha', 'Chhindwara', 'Damoh', 'Mandsaur', 'Khargone', 'Neemuch', 'Pithampur', 'Hoshangabad', 'Itarsi', 'Sehore', 'Betul', 'Seoni', 'Datia'],
        'Maharashtra': ['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Vasai-Virar', 'Aurangabad', 'Solapur', 'Bhiwandi', 'Amravati', 'Nanded', 'Kolhapur', 'Sangli', 'Jalgaon', 'Akola', 'Latur', 'Dhule', 'Ahmednagar', 'Ichalkaranji', 'Chandrapur', 'Parbhani', 'Jalna', 'Bhusawal', 'Navi Mumbai', 'Panvel', 'Satara', 'Beed', 'Yavatmal', 'Kamptee', 'Gondia', 'Barshi'],
        'Manipur': ['Imphal', 'Thoubal', 'Kakching', 'Bishnupur', 'Lilong', 'Mayang Imphal', 'Churachandpur', 'Sugnu', 'Nambol', 'Kakching', 'Moijing'],
        'Meghalaya': ['Shillong', 'Tura', 'Jowai', 'Nongpoh', 'Nongstoin', 'Williamnagar', 'Baghmara', 'Resubelpara', 'Mankachar', 'Khliehriat', 'Amlarem'],
        'Mizoram': ['Aizawl', 'Lunglei', 'Saiha', 'Champhai', 'Kolasib', 'Serchhip', 'Lawngtlai', 'Saitual', 'Khawzawl'],
        'Nagaland': ['Kohima', 'Dimapur', 'Mokokchung', 'Tuensang', 'Wokha', 'Zunheboto', 'Phek', 'Kiphire', 'Longleng'],
        'Odisha': ['Bhubaneswar', 'Cuttack', 'Rourkela', 'Berhampur', 'Sambalpur', 'Puri', 'Balasore', 'Bhadrak', 'Baripada', 'Bolangir', 'Jharsuguda', 'Jeypore', 'Kendujhar', 'Bargarh', 'Rayagada', 'Bhawanipatna', 'Koraput', 'Paradeep', 'Jagatsinghpur', 'Angul', 'Dhenkanal', 'Nabarangpur', 'Sunabeda', 'Titlagarh', 'Kalahandi', 'Boudh', 'Keonjhar', 'Nayagarh', 'Phulbani', 'Baleshwar'],
        'Puducherry': ['Puducherry', 'Karaikal', 'Mahe', 'Yanam'],
        'Punjab': ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda', 'Hoshiarpur', 'Mohali', 'Pathankot', 'Moga', 'Batala', 'Barnala', 'Firozpur', 'Kapurthala', 'Phagwara', 'Abohar', 'Muktsar', 'Bathinda', 'Barnala', 'Gurdaspur', 'Sangrur', 'Khanna', 'Nabha', 'Malout', 'Rajpura', 'Firozpur', 'Kharar', 'Jagraon', 'Faridkot', 'Fazilka'],
        'Rajasthan': ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner', 'Ajmer', 'Sikar', 'Alwar', 'Bhilwara', 'Bharatpur', 'Sri Ganganagar', 'Pali', 'Chittorgarh', 'Tonk', 'Kishangarh', 'Beawar', 'Hanumangarh', 'Dausa', 'Deogarh', 'Barmer', 'Nagaur', 'Sikar', 'Jhunjhunu', 'Churu', 'Baran', 'Sawai Madhopur', 'Karauli', 'Bundi', 'Jalore'],
        'Sikkim': ['Gangtok', 'Namchi', 'Mangan', 'Rangpo', 'Singtam', 'Gyalshing', 'Naya Bazar', 'Soreng', 'Pelling', 'Ravangla', 'Nayabazar', 'Jorethang', 'Geyzing', 'Rongli', 'Rhenock', 'Soreng', 'Yuksam', 'Soreng', 'Singtam', 'Singtam', 'Ravangla', 'Singtam', 'Jorethang', 'Gangtok', 'Gyalshing', 'Gangtok', 'Gyalshing', 'Naya Bazar', 'Namchi', 'Rangpo'],
        'Tamil Nadu': ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem', 'Tirunelveli', 'Tiruppur', 'Ranipet', 'Nagercoil', 'Vellore', 'Thoothukudi', 'Dindigul', 'Thanjavur', 'Tiruvannamalai', 'Hosur', 'Avadi', 'Salem', 'Erode', 'Tirunelveli', 'Nagercoil', 'Salem', 'Tiruppur', 'Ambattur', 'Avadi', 'Tiruvottiyur', 'Salem', 'Tirunelveli', 'Salem', 'Tiruppur', 'Salem', 'Nagercoil'],
        'Telangana': ['Hyderabad', 'Warangal', 'Nizamabad', 'Khammam', 'Karimnagar', 'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Jagtial', 'Nizamabad', 'Khammam', 'Karimnagar', 'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Jagtial', 'Nizamabad', 'Khammam', 'Karimnagar', 'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Jagtial', 'Nizamabad', 'Khammam', 'Karimnagar', 'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Jagtial', 'Nizamabad', 'Khammam', 'Karimnagar', 'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Jagtial', 'Nizamabad', 'Khammam', 'Karimnagar', 'Ramagundam', 'Mahbubnagar', 'Nalgonda', 'Adilabad', 'Suryapet', 'Miryalaguda', 'Jagtial'],
        'Tripura': ['Agartala', 'Udaipur', 'Dharmanagar', 'Kailasahar', 'Belonia', 'Sabroom', 'Sonamura', 'Khowai', 'Amarpur', 'Ambassa', 'Kumarghat', 'Santir Bazar', 'Bishalgarh', 'Teliamura', 'Jirania', 'Boxanagar', 'Melaghar', 'Khowai', 'Amarpur', 'Ambassa', 'Kumarghat', 'Santir Bazar', 'Bishalgarh', 'Teliamura', 'Jirania', 'Boxanagar', 'Melaghar'],    
        'Uttar Pradesh': ['Agra', 'Aligarh', 'Allahabad', 'Ambedkar Nagar', 'Amethi', 'Amroha', 'Auraiya', 'Azamgarh', 'Baghpat', 'Bahraich', 'Ballia', 'Balrampur', 'Banda', 'Barabanki', 'Bareilly', 'Basti', 'Bhadohi', 'Bijnor', 'Budaun', 'Bulandshahr', 'Chandauli', '...unpur', 'Shamli', 'Shravasti', 'Siddharthnagar', 'Sitapur', 'Sonbhadra', 'Sultanpur', 'Unnao', 'Varanasi'],
        'Uttarakhand': ['Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun', 'Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri', 'Udham Singh Nagar', 'Uttarkashi','Haridwar', 'Nainital', 'Pauri Garhwal', 'Pithoragarh', 'Rudraprayag', 'Tehri', 'Almora', 'Bageshwar', 'Chamoli', 'Champawat', 'Dehradun'],
        'West Bengal': ['Kolkata', 'Asansol', 'Siliguri', 'Durgapur', 'Bardhaman', 'English Bazar', 'Baharampur', 'Habra', 'Kharagpur', 'Shantipur', 'Dankuni', 'Dhulian', 'Ranaghat', 'Haldia', 'Raiganj', 'Krishnanagar', 'Nabadwip', 'Medinipur', 'Jalpaiguri', 'Balurghat', 'Bankura', 'Darjeeling', 'Purulia', 'Alipurduar', 'Jangipur', 'Cooch Behar', 'Malda', 'Adra', 'Asansol', 'Dum Dum', 'Jalpaiguri', 'Kharagpur', 'Shantipur', 'South Dum Dum', 'Titagarh', 'Habra', 'Naihati'],
    };

    module.exports = { statesList, citiesByState };